namespace Maui.PasswordMeter.Converters;

// Generated by IconFont2Code: https://andreinitescu.github.io/IconFont2Code
// If you change the class to 'public' in order to use it outside its assembly
//  you should also change the fields from 'const' to 'public static readonly'
public static class Smileys
{
	public static readonly string Smile = "\uf118";
	public static readonly string Frown = "\uf119";
	public static readonly string Meh = "\uf11a";
	public static readonly string SmileBeam = "\uf5b8";
	public static readonly string GrinStars = "\uf587";
	public static readonly string Grin = "\uf580";
}
